kind: Deployment
apiVersion: apps/v1
metadata:
  name: moviecollection
  namespace: trip
  labels:
    app: moviecollection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moviecollection
  template:
    metadata:
       labels:
         app: moviecollection
    spec:
      containers:
        - name: moviecollection
          image: image-registry.openshift-image-registry.svc.cluster.local:5000/trip/moviecollection:0.3
 
