apiVersion: v1
kind: Service
metadata:
  labels:
    deployment: moviecollection
  name: moviecollection-lb
  namespace: trip
spec:
  ports:
  - name: http
    nodePort: 30831
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: moviecollection
  type: LoadBalancer
