apiVersion: v1
kind: Service
metadata:
  labels:
    app: moviecollection
  name: moviecollection
  namespace: trip
  annotations:
    metallb.universe.tf/address-pool: metallb-pool-239
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: moviecollection
  type: LoadBalancer
